### PR TITLE
Parse HTML comment nodes

### PR DESCRIPTION
**Pull request by timkendrick**
This PR ensures that HTML `<!-- comment -->` nodes show up in the virtual DOM tree and are rendered to the DOM output correctly.

I've tried to match the code style based on what I saw in the rest of the library, let me know if I need to make any code style changes.

Two points I wasn't sure of:

- Whether to put the `vcomment.js` file in a separate folder (e.g. `lib/`)
- How to generate the `bundle.js` file

Let me know if there's anything else I can do to help get this merged!

### CODE REVIEW

**Comment by marcelklehr** [comment]
Looks good at first glance.

I take it, this is compatible with the main virtual-dom system, there's no built-in support/commonly used module for HTML comments?

**Comment by timkendrick** [comment]
Yeah, I'd personally prefer it if virtual-dom supported comment nodes internally, but from digging through the [source](https://github.com/Matt-Esch/virtual-dom/tree/master/vnode) it appears they've only got two types of nodes: `VNode` and `VText`.

Presumably this is an attempt to keep it simple and implementation-agnostic. I guess you could see comment nodes as more of a luxury HTML extra (like `DocumentFragments` or `DocumentType` elements).

Looking through virtual-dom's issues page, it looks like people are [recommending the same approach](https://github.com/Matt-Esch/virtual-dom/issues/301#issuecomment-137864950) of creating a custom widget for comment nodes, and keeping this out of virtual-dom core functionality.

**Comment by timkendrick** [comment]
...just read in the virtual-dom [docs](https://github.com/Matt-Esch/virtual-dom/blob/master/docs/widget.md#widget-interface) that a widget's `type` must be `"Widget"`.

I've updated the PR to reflect this.

**Comment by marcelklehr** [comment]
Thank you very much! :star2:

**Pull request merged**
