### PR TITLE
properly handle attributes instead of deleting them

### PR DESCRIPTION
**Pull request by jesseditson**
adds support for attribtues on a dom node so they will be correctly converted to vdom attributes.

### CODE REVIEW

**Comment by marcelklehr** [comment]
Does this work the other way 'round? e.g. if you render the resulting vnode, does it have those attributes set?

**Comment by marcelklehr** [comment]
It does work! https://github.com/Matt-Esch/virtual-dom/blob/master/vdom/apply-properties.js#L57

**Comment by marcelklehr** [comment]
Thank you!

**Comment by jesseditson** [comment]
Ah, sorry about dragging my feet on testing that, thanks for the merge!



—

**Pull request merged**
